
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for WebhookResource.
.Description
Create an in-memory object for WebhookResource.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.Acat.Models.Api20230215Preview.IWebhookResource
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

PARAMETER <IWebhookResource>: A class represent an AppComplianceAutomation webhook resource.
  EnableSslVerification <EnableSslVerification>: whether to enable ssl verification
  Event <NotificationEvent[]>: under which event notification should be sent.
  PayloadUrl <String>: webhook payload url
  SendAllEvent <SendAllEvents>: whether to send notification under any event.
  Status <WebhookStatus>: Webhook status.
  [SystemDataCreatedAt <DateTime?>]: The timestamp of resource creation (UTC).
  [SystemDataCreatedBy <String>]: The identity that created the resource.
  [SystemDataCreatedByType <CreatedByType?>]: The type of identity that created the resource.
  [SystemDataLastModifiedAt <DateTime?>]: The timestamp of resource last modification (UTC)
  [SystemDataLastModifiedBy <String>]: The identity that last modified the resource.
  [SystemDataLastModifiedByType <CreatedByType?>]: The type of identity that last modified the resource.
  [UpdateWebhookKey <UpdateWebhookKey?>]: whether to update webhookKey.
  [WebhookKey <String>]: webhook secret token. If not set, this field value is null; otherwise, please set a string value.
.Link
https://learn.microsoft.com/powershell/module/az.acat/new-azacatwebhookresourceobject
#>
function New-AzAcatWebhookResourceObject {
[OutputType([Microsoft.Azure.PowerShell.Cmdlets.Acat.Models.Api20230215Preview.IWebhookResource])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter()]
    [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.Acat.Support.EnableSslVerification])]
    [Microsoft.Azure.PowerShell.Cmdlets.Acat.Support.EnableSslVerification]
    # whether to enable ssl verification
    ${EnableSslVerification},

    [Parameter()]
    [System.Boolean]
    # whether to disable webhook
    ${Disable},

    [Parameter()]
    [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.Acat.Support.SendAllEvents])]
    [Microsoft.Azure.PowerShell.Cmdlets.Acat.Support.SendAllEvents]
    # whether to send notification under any event.
    ${TriggerMode},

    [Parameter()]
    [AllowEmptyCollection()]
    [ArgumentCompleter([Microsoft.Azure.PowerShell.Cmdlets.Acat.Support.NotificationEvent])]
    [Microsoft.Azure.PowerShell.Cmdlets.Acat.Support.NotificationEvent[]]
    # under which event notification should be sent.
    ${Events},

    [Parameter()]
    [System.String]
    # webhook payload url
    ${PayloadUrl},

    [Parameter()]
    [System.String]
    # content type
    ${ContentType},

    [Parameter()]
    [System.String]
    # webhook secret token.
    # If not set, this field value is null; otherwise, please set a string value.
    ${Secret}
)

process {
    
}
}
